name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12.3
        run: sudo xcode-select -s /Applications/Xcode_12.3.app
      - name: Run tests
        run: make test
